---
- import_tasks: custom_facts.yml
  become: true

- import_tasks: Darwin.yml
  when: ansible_os_family == "Darwin"

- import_tasks: Debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: RedHat.yml
  when: ansible_os_family == "RedHat"

- import_tasks: install.yml
  become: true
  become_user: "{{ pyenv_owner }}"
  when: pyenv_env == "user"

- import_tasks: install.yml
  become: true
  when: pyenv_env == "system"
